# The Docker image that will be used to build your app
image: alpine:latest

createpages:
  stage: deploy
  script:
    - echo "DÃ©ploiement des pages..."
  artifacts:
    paths:
      - public
  only:
    - master
  